// Asset mappings for apple-mobile
export const IMAGES = {
  hero14Pro: require('../assets/images/iphone-14-pro-hero.png'),
  hero14ProPhones: require('../assets/images/iphone-14-pro-phones.png'),
  hero14Arc: require('../assets/images/iphone-14-hero-arc.png'),
  heroSE: require('../assets/images/iphone-se-phones.jpg'),
  guidedTourNyc: require('../assets/images/guided-tour-nyc.jpg'),
  guidedTourBg: require('../assets/images/guided-tour-bg.jpg'),
  whyAppleBanner: require('../assets/images/why-apple-banner.jpg'),
  tradeInBanner: require('../assets/images/trade-in-banner.png'),
  tradeInHands: require('../assets/images/trade-in-hands.png'),
  waysToSaveCarrier: require('../assets/images/ways-to-save-carrier.png'),
  waysToSaveAppleCard: require('../assets/images/ways-to-save-applecard.png'),
  magsafeAccessories: require('../assets/images/magsafe-accessories.jpg'),
  airtagAccessories: require('../assets/images/airtag-accessories.jpg'),
  airpodsFamily: require('../assets/images/airpods-family.jpg'),
  appleOneGrid: require('../assets/images/apple-one-grid.png'),
  appleTvShows: require('../assets/images/apple-tv-shows.jpg'),
  musicThrowback: require('../assets/images/music-throwback.jpg'),
  musicGoodVibes: require('../assets/images/music-goodvibes.jpg'),
  appleMusicCovers: require('../assets/images/apple-music-covers.png'),
  appleNewsMagazines: require('../assets/images/apple-news-magazines.png'),
  appleArcadeJoystick: require('../assets/images/apple-arcade-joystick.jpg'),
  appleFitnessWorkout: require('../assets/images/apple-fitness-workout.jpg'),
  appleGiftCards: require('../assets/images/apple-gift-cards.jpg'),
  appleResearchIphones: require('../assets/images/apple-research-iphones.png'),
  ios16Phones: require('../assets/images/ios16-phones.jpg'),
  switchPhones: require('../assets/images/switch-phones.jpg'),
};
