// Comprehensive Catalog Data for Apple Mobile App (Apple-04 Recreated)
import { IMAGES } from './assets';

export const PROMO_RIBBON = {
  text: 'Get $200–$650 in credit when you trade in iPhone 11 or higher.',
  linkText: 'Shop iPhone',
};

export const CHAPTER_NAV_ITEMS = [
  { id: '14pro', name: 'iPhone 14 Pro', tag: 'New', icon: '📱' },
  { id: '14', name: 'iPhone 14', tag: 'New', icon: '📱' },
  { id: '13', name: 'iPhone 13', tag: '', icon: '📱' },
  { id: 'se', name: 'iPhone SE', tag: '', icon: '📱' },
  { id: 'compare', name: 'Compare', tag: '', icon: '⚖️' },
  { id: 'airpods', name: 'AirPods', tag: '', icon: '🎧' },
  { id: 'airtag', name: 'AirTag', tag: '', icon: '🏷️' },
  { id: 'accessories', name: 'Accessories', tag: '', icon: '🔌' },
  { id: 'card', name: 'Apple Card', tag: '', icon: '💳' },
];

export const IPHONE_MODELS = [
  {
    id: '14pro',
    name: 'iPhone 14 Pro',
    tagline: 'The ultimate iPhone.',
    headline: 'Pro. Beyond.',
    price: 999,
    monthlyPrice: 41.62,
    badge: 'New',
    theme: 'dark',
    heroImage: IMAGES.hero14ProPhones,
    colors: [
      { name: 'Deep Purple', hex: '#594f63', image: IMAGES.hero14ProPhones },
      { name: 'Gold', hex: '#fae7cf', image: IMAGES.hero14ProPhones },
      { name: 'Silver', hex: '#f1f2ed', image: IMAGES.hero14ProPhones },
      { name: 'Space Black', hex: '#403e3d', image: IMAGES.hero14ProPhones },
    ],
    display: '6.7″ or 6.1″ Super Retina XDR with ProMotion & Always-On display',
    island: 'Dynamic Island',
    camera: 'Pro camera system (48MP Main | Ultra Wide | Telephoto)',
    chip: 'A16 Bionic chip (6-core CPU, 5-core GPU, 16-core Neural Engine)',
    battery: 'Up to 29 hours video playback',
    safety: 'Emergency SOS via satellite & Crash Detection',
    biometrics: 'Face ID',
    connectivity: 'Superfast 5G cellular',
  },
  {
    id: '14',
    name: 'iPhone 14',
    tagline: 'A total powerhouse.',
    headline: 'Wonderfull.',
    price: 799,
    monthlyPrice: 33.29,
    badge: 'New',
    theme: 'light',
    heroImage: IMAGES.hero14Arc,
    colors: [
      { name: 'Yellow', hex: '#fbe277', image: IMAGES.hero14Arc },
      { name: 'Blue', hex: '#a0b4c7', image: IMAGES.hero14Arc },
      { name: 'Purple', hex: '#e3dbe7', image: IMAGES.hero14Arc },
      { name: 'Midnight', hex: '#222930', image: IMAGES.hero14Arc },
      { name: 'Starlight', hex: '#faf7f2', image: IMAGES.hero14Arc },
      { name: '(PRODUCT)RED', hex: '#fc3c44', image: IMAGES.hero14Arc },
    ],
    display: '6.7″ or 6.1″ Super Retina XDR display',
    island: 'Classic Notch',
    camera: 'Advanced dual-camera system (12MP Main | Ultra Wide)',
    chip: 'A15 Bionic chip with 5-core GPU',
    battery: 'Up to 26 hours video playback',
    safety: 'Emergency SOS via satellite & Crash Detection',
    biometrics: 'Face ID',
    connectivity: 'Superfast 5G cellular',
  },
  {
    id: '13',
    name: 'iPhone 13',
    tagline: 'As amazing as ever.',
    headline: 'Your new superpower.',
    price: 599,
    monthlyPrice: 24.95,
    badge: '',
    theme: 'light',
    heroImage: IMAGES.hero14Arc,
    colors: [
      { name: 'Green', hex: '#3b5240', image: IMAGES.hero14Arc },
      { name: 'Pink', hex: '#fae0dc', image: IMAGES.hero14Arc },
      { name: 'Blue', hex: '#215e7d', image: IMAGES.hero14Arc },
      { name: 'Midnight', hex: '#232a31', image: IMAGES.hero14Arc },
      { name: 'Starlight', hex: '#fbf7f4', image: IMAGES.hero14Arc },
      { name: '(PRODUCT)RED', hex: '#bf0013', image: IMAGES.hero14Arc },
    ],
    display: '6.1″ or 5.4″ Super Retina XDR display',
    island: 'TrueDepth Notch',
    camera: 'Dual-camera system (12MP Main | Ultra Wide)',
    chip: 'A15 Bionic chip with 4-core GPU',
    battery: 'Up to 19 hours video playback',
    safety: 'Emergency SOS',
    biometrics: 'Face ID',
    connectivity: 'Superfast 5G cellular',
  },
  {
    id: 'se',
    name: 'iPhone SE',
    tagline: 'Serious power. Serious value.',
    headline: 'Love the power.\nLove the value.',
    price: 429,
    monthlyPrice: 17.87,
    badge: '',
    theme: 'light',
    heroImage: IMAGES.heroSE,
    colors: [
      { name: 'Midnight', hex: '#191f26', image: IMAGES.heroSE },
      { name: 'Starlight', hex: '#f4f0eb', image: IMAGES.heroSE },
      { name: '(PRODUCT)RED', hex: '#ba0c2f', image: IMAGES.heroSE },
    ],
    display: '4.7″ Retina HD display',
    island: 'Home Button Design',
    camera: '12MP Main camera with Smart HDR 4',
    chip: 'A15 Bionic chip',
    battery: 'Up to 15 hours video playback',
    safety: 'Emergency SOS',
    biometrics: 'Touch ID',
    connectivity: 'Fast 5G cellular',
  },
];

export const TRADE_IN_DEVICES = [
  { model: 'iPhone 13 Pro Max', value: 650 },
  { model: 'iPhone 13 Pro', value: 570 },
  { model: 'iPhone 13', value: 400 },
  { model: 'iPhone 12 Pro Max', value: 420 },
  { model: 'iPhone 12', value: 300 },
  { model: 'iPhone 11', value: 200 },
  { model: 'Other / No Trade-in', value: 0 },
];

export const BENTO_PERKS = [
  {
    id: 'trade-in',
    title: 'Save up to $800 on iPhone 14 or iPhone 14 Pro with carrier deals.',
    subtitle: 'Or get $200–$650 in credit when you trade in your current iPhone directly with Apple.',
    badge: 'Apple Trade In',
    linkText: 'Find your trade-in value',
    icon: '🔁',
  },
  {
    id: 'apple-card',
    title: 'Pay 0% APR over 24 months with Apple Card.',
    subtitle: 'Choose Apple Card Monthly Installments at checkout and get 3% Daily Cash back up front.',
    badge: 'Apple Card',
    linkText: 'Learn more about financing',
    icon: '💳',
  },
  {
    id: 'delivery',
    title: 'Free delivery, or pickup in two hours.',
    subtitle: 'Get free next-day delivery on any in-stock iPhone, or pick it up at your local Apple Store in as little as 2 hours.',
    badge: 'Delivery & Pickup',
    linkText: 'Check availability',
    icon: '📦',
  },
  {
    id: 'specialist',
    title: 'Shop one-on-one with a Specialist online.',
    subtitle: 'Connect with an Apple Specialist over chat or one-way video to find the ideal iPhone and plan for you.',
    badge: 'Personalized Help',
    linkText: 'Ask a Specialist',
    icon: '💬',
  },
];

export const VALUE_PROPS = [
  {
    title: 'Fast, free delivery',
    desc: 'Or two-hour walk-in pickup at an Apple Store.',
    link: 'Learn more',
    icon: 'box',
  },
  {
    title: 'Pay monthly at 0% APR',
    desc: 'Choose Apple Card Monthly Installments when you check out.',
    link: 'Learn more',
    icon: 'card',
  },
  {
    title: 'Get help buying',
    desc: 'Have a question? Call a Specialist or chat online.',
    link: 'Contact us',
    icon: 'specialist',
  },
];

export const MAGSAFE_ITEMS = [
  {
    id: 'magsafe-silicone',
    name: 'iPhone 14 Silicone Case with MagSafe',
    category: 'Cases',
    price: 49,
    colors: ['#efdb5e', '#7c8fa3', '#493751', '#2c333a', '#eb685b'],
    image: IMAGES.magsafeAccessories,
  },
  {
    id: 'magsafe-leather',
    name: 'iPhone 14 Pro Leather Case with MagSafe',
    category: 'Cases',
    price: 59,
    colors: ['#49392e', '#23303d', '#483c4f', '#252527'],
    image: IMAGES.magsafeAccessories,
  },
  {
    id: 'magsafe-wallet',
    name: 'iPhone Leather Wallet with MagSafe',
    category: 'Wallets',
    price: 59,
    colors: ['#806a59', '#3e4b3c', '#2c2b2e', '#e77b4f'],
    image: IMAGES.magsafeAccessories,
  },
  {
    id: 'magsafe-battery',
    name: 'MagSafe Battery Pack',
    category: 'Power',
    price: 99,
    colors: ['#f2f2f4'],
    image: IMAGES.magsafeAccessories,
  },
  {
    id: 'airtag',
    name: 'AirTag (1 Pack)',
    category: 'AirTag',
    price: 29,
    colors: ['#ffffff'],
    image: IMAGES.airtagAccessories,
  },
];

export const AUDIO_ITEMS = [
  {
    id: 'airpods-pro',
    name: 'AirPods Pro (2nd generation)',
    price: 249,
    tagline: 'Rebuilt from the sound up.',
    highlights: 'Active Noise Cancellation, Adaptive Transparency, Personalized Spatial Audio',
    image: IMAGES.airpodsFamily,
  },
  {
    id: 'airpods-3',
    name: 'AirPods (3rd generation)',
    price: 169,
    tagline: 'It’s magic, remastered.',
    highlights: 'Spatial Audio with dynamic head tracking, Sweat & water resistant',
    image: IMAGES.airpodsFamily,
  },
  {
    id: 'airpods-max',
    name: 'AirPods Max',
    price: 549,
    tagline: 'High-fidelity audio. Active Noise Cancellation.',
    highlights: 'Apple-designed dynamic driver, Computational audio, Digital Crown',
    image: IMAGES.airpodsFamily,
  },
];

export const ACCESSORIES = [
  ...MAGSAFE_ITEMS,
  {
    id: 'airpods-pro',
    name: 'AirPods Pro (2nd generation)',
    category: 'Audio',
    price: 249,
    colors: ['#ffffff'],
    image: IMAGES.airpodsFamily,
  },
  {
    id: 'airpods-3',
    name: 'AirPods (3rd generation)',
    category: 'Audio',
    price: 169,
    colors: ['#ffffff'],
    image: IMAGES.airpodsFamily,
  },
  {
    id: 'airpods-max',
    name: 'AirPods Max',
    category: 'Audio',
    price: 549,
    colors: ['#2c2c2e', '#e3e4e6', '#f3d9d5', '#d4e1d5', '#dfe6ef'],
    image: IMAGES.airpodsFamily,
  },
];

export const SERVICES_ITEMS = [
  {
    id: 'one',
    title: 'One',
    headline: 'Bundle up to six Apple services.\nAnd enjoy more for less.',
    desc: 'Try it free or Learn more',
    image: IMAGES.appleOneGrid,
    theme: 'light',
  },
  {
    id: 'tv',
    title: 'tv+',
    headline: 'Get 3 months of Apple TV+ free when you buy an iPhone.',
    image: IMAGES.appleTvShows,
    theme: 'dark',
  },
  {
    id: 'music',
    title: 'Music',
    headline: 'Over 100 million songs. Start listening for free today.',
    image: IMAGES.musicThrowback,
    theme: 'light',
  },
  {
    id: 'news',
    title: 'News+',
    headline: 'Get 3 months of Apple News+ free when you buy an iPhone.',
    image: IMAGES.appleNewsMagazines,
    theme: 'light',
  },
  {
    id: 'arcade',
    title: 'Arcade',
    headline: 'Get 3 months of Apple Arcade free when you buy an iPhone.',
    image: IMAGES.appleArcadeJoystick,
    theme: 'light',
  },
  {
    id: 'fitness',
    title: 'Fitness+',
    headline: 'Fitness for everyone. Now all you need is iPhone.',
    image: IMAGES.appleFitnessWorkout,
    theme: 'light',
  },
  {
    id: 'giftcard',
    title: 'Gift Card',
    headline: 'For everything and everyone.',
    image: IMAGES.appleGiftCards,
    theme: 'light',
  },
  {
    id: 'research',
    title: 'Research app',
    headline: 'Introducing the Apple Research app.\nThe future of health research is you.',
    image: IMAGES.appleResearchIphones,
    theme: 'light',
  },
];
